In [1]:
from lit_llama import model
import torch

c:\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Python311\Lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: p is an invalid version and will not be supported in a future release
  warnings.warn(


In [2]:
# Get embedding
embedding = torch.nn.Embedding(32000,4096)
embedding.load_state_dict(torch.load('embedding.pt', map_location=torch.device('cpu') ))

<All keys matched successfully>

In [3]:
import sys
import time
import warnings
from pathlib import Path
from typing import Optional

import lightning as L
import torch


from lit_llama import LLaMA, Tokenizer
from lit_llama.utils import EmptyInitOnDevice, lazy_load, llama_model_lookup



In [4]:
tokenizer = Tokenizer('checkpoints/lit-llama/tokenizer.model')
encoded = tokenizer.encode('hello', bos=True, eos=False)

In [11]:
print(tokenizer.encode('hello', bos=True, eos=False))

tensor([    1, 22172,     2], dtype=torch.int32)


In [5]:
encoded

tensor([    1, 22172], dtype=torch.int32)

In [34]:
embedding(encoded)

tensor([[ 0.0153, -0.0121,  0.0125,  ...,  0.0131,  0.0072, -0.0007],
        [-0.0132, -0.0003, -0.0206,  ...,  0.0376, -0.0197, -0.0162]],
       grad_fn=<EmbeddingBackward0>)

In [47]:
del t
del tl

In [48]:
import torch.nn as nn
tl = nn.TransformerEncoderLayer(d_model=4096, nhead=4, dim_feedforward=4096)
t = nn.TransformerEncoder(tl, 2)


RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 201326592 bytes.

In [44]:
t(embedding(encoded))

tensor([[ 0.4183, -1.2087,  1.0354,  ...,  0.0256, -0.4461, -0.0277],
        [-0.7472, -0.8502,  0.0380,  ...,  0.3839, -1.3298, -0.2397]],
       grad_fn=<NativeLayerNormBackward0>)