In [20]:
import sys
import time
import warnings
from pathlib import Path
from typing import Optional

import lightning as L
import torch

# support running without installing as a package


from lit_llama import LLaMA, Tokenizer
from lit_llama.utils import EmptyInitOnDevice, lazy_load, llama_model_lookup

import generate

c:\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Python311\Lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: p is an invalid version and will not be supported in a future release
  warnings.warn(


In [13]:
config = model.LLaMAConfig.from_name('7B')

In [1]:
import pandas as pd

In [3]:
df = pd.read_json("alpaca_data_cleaned.json")

In [23]:
t = torch.Tensor([1,2,3]).type(torch.float16)

In [28]:
torch.cuda.BFloat16Tensor

torch.cuda.BFloat16Tensor

In [34]:
torch.cuda.BFloat16Tensor(t)

TypeError: type torch.cuda.BFloat16Tensor not available. Torch not compiled with CUDA enabled.

In [37]:
torch.bfloat16

torch.bfloat16

In [9]:
df['instruction'][51758]

"I will give you a list of steps.  You need to determine if the steps are going forwards or backwards in time by outputting 'Forwards' or 'Backwards'."

In [18]:
for index, row in df[:100].iterrows():
    print(index)
    #print(row['instruction'], row['input'], row['output'], sep='\n')
   

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [2]:

import json

with open('alpaca_data_cleaned.json', 'r') as f:
  data = json.load(f)

In [4]:
data[0]

{'instruction': 'Give three tips for staying healthy.',
 'input': '',
 'output': '1. Eat a balanced and nutritious diet: Make sure your meals are inclusive of a variety of fruits and vegetables, lean protein, whole grains, and healthy fats. This helps to provide your body with the essential nutrients to function at its best and can help prevent chronic diseases.\n\n2. Engage in regular physical activity: Exercise is crucial for maintaining strong bones, muscles, and cardiovascular health. Aim for at least 150 minutes of moderate aerobic exercise or 75 minutes of vigorous exercise each week.\n\n3. Get enough sleep: Getting enough quality sleep is crucial for physical and mental well-being. It helps to regulate mood, improve cognitive function, and supports healthy growth and immune function. Aim for 7-9 hours of sleep each night.'}

In [5]:
from lit_llama import model

In [15]:
block = model.Block(config)

In [16]:
def count_params(model):
    params = 0
    for p in model.parameters():
        params += p.numel()

    print(params)

count_params(block)

202383360


In [19]:
t = torch.randn(1,10,4096)
block(t).shape

torch.Size([1, 10, 4096])

In [17]:
tokenizer = Tokenizer('./checkpoints/llama/tokenizer.model')

In [21]:
tokenizer.encode('''Q: Roger has 5 tennis balls. He buys 2 more cans of
                tennis balls. Each can has 3 tennis balls. How many
                tennis balls does he have now?
                A: Roger started with 5 balls. 2 cans of 3 tennis balls
                each is 6 tennis balls. 5 + 6 = 11. The answer is 11'''
                 ).shape

torch.Size([88])

In [23]:
tokenizer.encode('''Q: The cafeteria had 23 apples. If they used 20 to
                make lunch and bought 6 more, how many apples
                do they have?''').shape

torch.Size([43])

In [24]:
88 + 43

131

In [28]:
preprompt = '''Q: Roger has 5 tennis balls. He buys 2 more cans of
                tennis balls. Each can has 3 tennis balls. How many
                tennis balls does he have now?
                A: Roger started with 5 balls. 2 cans of 3 tennis balls
                each is 6 tennis balls. 5 + 6 = 11. The answer is 11.
               '''

query = '''Q: The cafeteria had 23 apples. If they used 20 to
            make lunch and bought 6 more, how many apples
            do they have?'''

In [30]:
print(preprompt + query)

Q: Roger has 5 tennis balls. He buys 2 more cans of
                tennis balls. Each can has 3 tennis balls. How many
                tennis balls does he have now?
                A: Roger started with 5 balls. 2 cans of 3 tennis balls
                each is 6 tennis balls. 5 + 6 = 11. The answer is 11.
               Q: The cafeteria had 23 apples. If they used 20 to
            make lunch and bought 6 more, how many apples
            do they have?


In [38]:
preds = torch.randn((1,32000,200))
targets = torch.randint(low=0,high=32000, size=(200,))

In [39]:
loss_fn = nn.NLLLoss()
loss_fn(preds,targets)

ValueError: Expected input batch_size (32000) to match target batch_size (200).

In [3]:
a = torch.randn((1,50,4096))

In [4]:
b = torch.zeros(4096)
b.shape

torch.Size([4096])

In [8]:
b.reshape(1,1,-1).shape

torch.Size([1, 1, 4096])

In [12]:
result = torch.cat((b.reshape(1,1,-1),a), dim=1)

In [13]:
result[:,0,:]

tensor([[0., 0., 0.,  ..., 0., 0., 0.]])

In [1]:
import torch
import torch.nn as nn

In [2]:
torch.zeros(10,10).reshape((1,-1))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]])

In [23]:
t = torch.zeros((32000, 1))

In [27]:
catted = torch.cat((t, torch.randn(32000, 1)), dim=1)

In [28]:
catted.shape

torch.Size([32000, 2])

In [30]:
catted.shape

torch.Size([32000, 2])

In [31]:
arr2 = torch.randint(low=0, high=32000, size=(1,2))
loss_fn(catted, arr2)

ValueError: Expected input batch_size (32000) to match target batch_size (1).

In [43]:
torch.zeros(size=(1,32000,1))

tensor([[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]])

In [33]:
arr1 = torch.randn(size=(1,32000, 1000))
arr2 = torch.randint(low=0, high=32000, size=(1,1000))

print('pred shape: ',arr1.shape)
print('target shape: ', arr2.shape)
loss_fn = nn.NLLLoss()
loss = loss_fn(arr1, arr2)

pred shape:  torch.Size([1, 32000, 1000])
target shape:  torch.Size([1, 1000])


In [39]:
out = torch.zeros(1, 32000, 1)

for i in range(10):
    out = torch.cat((out, torch.randn(1,32000,1)), dim=2)

out = out[:,:,:-1]

In [40]:
out.shape

torch.Size([1, 32000, 10])

In [41]:
target = torch.randint(low=0, high=32000, size=(1,10))
loss = loss_fn(out, target)